name: Jason Linker
favicon: null
layout_spectrum: 0.30043592932634056
typography_spectrum: 0.8339906351175159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8209262590389699
  lightness: 0.4684580494649708
  saturation: 0.286029931390658
  rhythmicContrast: 0.17767483065836132
purpose: []
